server:
  port: 8090

spring:
  application:
    name: yb-log
  profiles:
    active: dev
  # MongoDB
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: admin123
      authentication-database: admin
      database: yb_log
  # RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 2s
          max-attempts: 3
  # Nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace:
        group: DEFAULT_GROUP
      config:
        server-addr: localhost:8848
        file-extension: yaml
        group: DEFAULT_GROUP
        refresh-enabled: true
        import-check:
          enabled: false

# Swagger / Knife4j
swagger:
  title: yb-log - 日志服务
  description: 行为日志 & 审计日志接口文档
  version: 1.0.0

springdoc:
  enable-spring-data-rest-support: false
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: default
      paths-to-match: "/**"

knife4j:
  enable: true
  setting:
    language: zh_cn

# 日志
logging:
  level:
    com.yb: debug
